version: '3.1'
services:
  db:
    image: mysql
    container_name: springboot2_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - springboot2_project:/var/lib/springboot2_mysql_container

volumes:
  springboot2_project: