server:
  error:
    include-stacktrace: ON_PARAM
    
spring:
  application:
    name: springboot2-project
  datasource:
    url: jdbc:mysql://localhost:3306/sys?createDataBaseIfNoExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update